---
"$id": http://example.com/example.json
type: object
required:
- id
- assignee
- summary
- content
- tags
- status
additionalProperties: true
properties:
  id:
    "$id": "#/properties/id"
    type: string
    title: The id schema
    description: An explanation about the purpose of this instance.
    default: ''
    examples:
    - T-123
  assignee:
    "$id": "#/properties/assignee"
    type: string
    title: The assignee schema
    description: An explanation about the purpose of this instance.
    default: ''
    examples:
    - '123'
  summary:
    "$id": "#/properties/summary"
    type: string
    title: The summary schema
    description: An explanation about the purpose of this instance.
    default: ''
    examples:
    - Task summary
  content:
    "$id": "#/properties/content"
    type: string
    title: The content schema
    description: An explanation about the purpose of this instance.
    default: ''
    examples:
    - Task content
  tags:
    "$id": "#/properties/tags"
    type: array
    title: The tags schema
    description: An explanation about the purpose of this instance.
    default: []
    examples:
    - - b2b
      - b2c
    items:
      type: string
      enum:
      - b2b
      - b2c
  status:
    "$id": "#/properties/status"
    type: string
    title: status
    description: status
    enum:
    - TODO
    - IN_PROGRESS
    - DONE
